const ROLES = {
    "Super Admin": {
        name: "Super Admin",
        isFileManager: true,
        canUploadFiles: true,
        canManageUsers: true,
        canManageGroups: true,
        canViewGroups: true,
        canViewRoles: true,
        canViewAnalytics: true,
        canManageEvents: true,
        canManageSettings: true,
        canManageFAQ: true,
        canManageQNA: true,
        isHidden: true,
        level: 4,
        activePhases: ["Hold", "Preparation", "Open"],
        viewableBy: [],
        viewableByDescription: "N/A",
        // This is a virtual role, not a real role
        virtualRole: true,
        showDataroomStorage: true,
    },
    "Contract Manager": {
        name: "Contract Manager",
        isFileManager: true,
        canUploadFiles: true,
        canManageUsers: true,
        canManageGroups: true,
        canViewGroups: true,
        canViewRoles: true,
        canViewAnalytics: true,
        canManageEvents: true,
        canManageSettings: true,
        canManageFAQ: true,
        canManageQNA: true,
        isHidden: false,
        level: 3,
        activePhases: ["Hold", "Preparation", "Open"],
        viewableBy: [
            "Manager",
            "Hidden Manager",
            "Publisher",
            "Previewer",
            "Reviewer",             
        ],
        viewableByDescription: "All",
        virtualRole: true,
        showDataroomStorage: false,
    },
    Manager: {
        name: "Manager",
        isFileManager: true,
        canUploadFiles: true,
        canManageUsers: true,
        canManageGroups: true,
        canViewGroups: true,
        canViewRoles: true,
        canViewAnalytics: true,
        canManageEvents: true,
        canManageSettings: true,
        canManageFAQ: true,
        canManageQNA: true,
        isHidden: false,
        level: 2,
        activePhases: ["Hold", "Preparation", "Open"],
        viewableBy: [
            "Manager",
            "Hidden Manager",
            "Publisher",
            "Previewer",
            "Reviewer",
        ],
        viewableByDescription: "All",
        virtualRole: false,
        showDataroomStorage: false,
    },
    "Hidden Manager": {
        name: "Hidden Manager",
        isFileManager: true,
        canUploadFiles: true,
        canManageUsers: true,
        canManageGroups: true,
        canViewGroups: true,
        canViewRoles: true,
        canManageFAQ: true,
        canManageQNA: true,
        canViewAnalytics: true,
        canManageEvents: true,
        canManageSettings: true,
        isHidden: true,
        level: 2,
        activePhases: ["Hold", "Preparation", "Open"],
        viewableBy: ["Manager", "Hidden Manager"],
        viewableByDescription: "Manager, Hidden Manager",
        virtualRole: false,
        showDataroomStorage: false,  
    },
    // "Manager Ltd": {
    //     name: "Manager Ltd",
    //     isFileManager: true,
    //     canUploadFiles: true,
    //     canManageUsers: true,
    //     canManageFAQ: true,
    //     canManageGroups: true,
    //     canViewAnalytics: true,
    //     canManageEvents: true,
    //     canManageSettings: false,
    //     isHidden: false,
    //     level: 6,
    //     activePhases: ["Hold", "Preparation", "Open"],
    //     viewableBy: [
    //         "Manager +",
    //         "Hidden Manager +",
    //         "Manager Ltd",
    //         "Publisher +",
    //         "Publisher",
    //         "Previewer",
    //         "Reviewer",
    //     ],
    //     viewableByDescription: "All",
    // },
    Publisher: {
        name: "Publisher",
        isFileManager: true,
        canUploadFiles: true,
        canManageUsers: false,
        canManageGroups: false,
        canViewGroups: true,
        canViewRoles: true,
        canManageEvents: false,
        canViewAnalytics: false,
        canManageSettings: false,
        canManageFAQ: false,
        canManageQNA: false,
        isHidden: false,
        level: 1,
        activePhases: ["Preparation", "Open"],
        viewableBy: [
            "Manager",
            "Hidden Manager",
            "Publisher",             //reviewer and previewer viewing removed 
        ],
        viewableByDescription: "Manager, Hidden Manager Publisher",
        virtualRole: false,
        showDataroomStorage: false,
    },
    // Publisher: {
    //     name: "Publisher",
    //     isFileManager: false,
    //     canUploadFiles: false,
    //     canManageUsers: false,
    //     canManageGroups: false,
    //     canViewAnalytics: false,
    //     canManageEvents: false,
    //     canManageSettings: false,
    //     canManageFAQ: false,
    //     isHidden: false,
    //     level: 4,
    //     activePhases: ["Preparation", "Open"],
    //     viewableBy: [
    //         "Manager +",
    //         "Hidden Manager +",
    //         "Manager Ltd",
    //         "Publisher +",
    //         "Publisher",
    //         "Previewer",
    //         "Reviewer",
    //     ],
    //     viewableByDescription: "All",
    // },
    Previewer: {
        name: "Previewer",
        isFileManager: false,
        canUploadFiles: false,
        canManageUsers: false,
        canManageGroups: false,
        canViewGroups: false,
        canViewRoles: false,
        canViewAnalytics: false,
        canManageEvents: false,
        canManageSettings: false,
        canManageFAQ: false,
        canManageQNA: false,
        isHidden: false,
        level: 1,
        activePhases: ["Preparation", "Open"],
        viewableBy: ["Manager", "Hidden Manager", "Publisher"],
        viewableByDescription: "Manager, Hidden Manager, Publisher",
        virtualRole: false,
        showDataroomStorage: false,
    },
    Reviewer: {
        name: "Reviewer",
        isFileManager: false,
        canUploadFiles: false,
        canManageUsers: false,
        canManageGroups: false,
        canViewGroups: false,
        canViewRoles: false,
        canViewAnalytics: false,
        canManageEvents: false,
        canManageSettings: false,
        canManageFAQ: false,
        canManageQNA: false,
        isHidden: false,
        level: 1,
        activePhases: ["Open"],
        viewableBy: ["Manager", "Hidden Manager", "Publisher"],
        viewableByDescription: "Manager, Hidden Manager, Publisher",
        virtualRole: false,
        showDataroomStorage: false,
    },
};

module.exports = { ROLES };
